development:
  adapter: postgresql
  database: pizza_time
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: pizza_time
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pizza_time
  pool: 5
  timeout: 5000
